export const FETCH_ROBOTS = "FETCH_ROBOTS";
export const EDIT_ROBOT = "EDIT_ROBOT";
export const ADD_SELECTED_ROBOT = "ADD_SELECTED_ROBOT";
export const REMOVE_SELECTED_ROBOT = "REMOVE_SELECTED_ROBOT";
export const SET_SELECTED_ROBOTS = "SET_SELECTED_ROBOTS";
